name: MomoKtviOS
options:
  bundleIdPrefix: com.momo
  deploymentTarget:
    iOS: "12.0"
  createIntermediateGroups: true
  projectFormat: Xcode 14.0
settings:
  base:
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    SDKROOT: iphoneos
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    IPHONEOS_DEPLOYMENT_TARGET: "12.0"
    ENABLE_BITCODE: NO
    SWIFT_OPTIMIZATION_LEVEL: "-Owholemodule"
targets:
  MomoKtviOS:
    type: application
    platform: iOS
    sources:
      - path: MomoKtviOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.momo.ktv.ios
        PRODUCT_NAME: "MomoKtviOS"
        INFOPLIST_FILE: "MomoKtviOS/Info.plist"
        ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
        TARGETED_DEVICE_FAMILY: "1,2"
