#!/bin/bash

FILE_PATH="${TRIM_APPDEST}/docker/docker-compose.yaml"
DOCKER_NAME="momo-ktv"

is_docker_running () {
    docker inspect "$DOCKER_NAME" 2>/dev/null | grep -q '"Status": "running",' || exit 1
    return
}

case $1 in
start)
    # docker 应用由应用中心负责启动，这里无需操作
    exit 0
    ;;
stop)
    exit 0
    ;;
status)
    if is_docker_running; then
        exit 0
    else
        exit 3
    fi
    ;;
*)
    exit 1
    ;;
esac
